version: '3'

services:
  oncology-trial-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount data directories for persistence
      - ./data:/app/data
      - ./reports:/app/reports
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      # Add any environment variables needed for the pipeline
    # Command can be overridden when running docker-compose
    command: python pipeline.py

  # Optional Jupyter service for interactive analysis
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''