name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # This job runs independently after the workflow is triggered
    # The python-tests workflow should be configured to run before this in GitHub
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Build documentation
      run: |
        # Example command to build documentation or reports
        # Replace with actual build commands for your project
        mkdir -p build/docs
        cp -r reports/* build/docs/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/docs
        publish_branch: gh-pages
        full_commit_message: Deploy documentation from ${{ github.sha }}